image_size: 640
classes: 
  - Eggtarts
  - Salmon Sashimi
  - Unknown
train:
  batch_size: 8
  epochs: 50
  learning_rate: 0.0001
  loss_function: categorical_crossentropy
paths:
  checkpoint_dir: "Checkpoint/"
  train_data: "Data/train"
  valid_data: "Data/valid"
  test_data: "Data/test"
  plots: "Plot/"
  saved_model: saved_model/
  logs: logs/
  output_dir: "output/"
