image_size: 128
classes: 
  - Eggtarts
  - Salmon Sashimi
  - Unknown
train:
  batch_size: 32
  epochs: 20
  learning_rate: 0.01
  loss_function: categorical_crossentropy
  optimizer: adam
paths:
  checkpoint_dir: "Checkpoint/"
  train_data: "Data/train"
  valid_data: "Data/valid"
  test_data: "Data/test"
  plots: "Plot/"
  saved_model: saved_model/
  logs: logs/
  output_dir: "output/"
