image_size: 224
classes: 
  - Eggtarts
  - Salmon Sashimi
  - Unknown
train:
  batch_size: 16
  epochs: 10
  learning_rate: 0.001
  loss_function: categorical_crossentropy
  optimizer: adam
paths:
  train_data: "Data/train"
  valid_data: "Data/valid"
  test_data: "Data/test"
  plots: "Plot/"
  saved_model: saved_model/
  logs: logs/
  output_dir: "output/"
